//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee_Course
    {
        public int Id { get; set; }
        public Nullable<int> TraineeId { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Trainee Trainee { get; set; }
    }
}
