//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.Trainee_Course = new HashSet<Trainee_Course>();
        }
    
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string Education { get; set; }
        public string ProLanguage { get; set; }
        public Nullable<int> ToeicScore { get; set; }
        public string Experience { get; set; }
        public string Location { get; set; }
        public string Department { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainee_Course> Trainee_Course { get; set; }
    }
}
